### ISSUE TITLE
Json to Google doesn't work

### ISSUE THREAD

**Issue by bebbolino** [Koalified/NewView#1]
Hi, i tried to run your code i my phone, but the POI doesn't appear.
I fixed some problems with app compact and Gradle in my Android Studio, but the call to Google Apis won't work.
I saw also that you were able to restyle the seek bar (Zoom bar). Reading the class AugmentedActivity i wasn't able to find where you customize the seek bar.

Can you please explain where you have customize it?

Thanks in advance.

Android on phone 5.1.1
Android studio 1.5.1 last build

**Comment by Koalified** [comment]
Hello, 

I can tell you right off the bat that the api key to access google places will need to be put in from your Google Developer Console (Located in app -> src -> main -> values -> keys -> browserkey). If you were just looking for a sample of the application, it may be found on Google Play by searching AR NewView.

The custom VerticalSeekbar is located under the CustomObjects subfolder if you would like to take a closer inspection.

A known bug with this version is the radar values are off. The Google Play version works spectacularly but in tinkering with Interfaces and polish, I have somehow thrown this value off. I was going to take a look at it in the New Year. So far, if you care to look, the error is being thrown in the Marker's check if it's on the radar method (Marker class)

Anyway, I'll post back when these issues are fixed and make a ReadMe. Happy New Year!

**Comment by bebbolino** [comment]
Hello, 
thanks for the kind reply. I was able to customize the VerticalSeekBar like i wanted. 
Thanks a lot for the help, I  appreciated.

Brus
